apiVersion: apps/v1
kind: Deployment
metadata:
  name: feast-feature-server
  namespace: ghosteam-v5
  labels:
    app: feast-feature-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feast-feature-server
  template:
    metadata:
      labels:
        app: feast-feature-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "6566"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: feast-server
        image: ghosteam/feast:latest
        ports:
        - containerPort: 6566
          name: http
        env:
        - name: FEAST_REDIS_URL
          value: "redis://redis-service:6379"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: s3-bucket
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 6566
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 6566
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: feast-config
          mountPath: /feast_repo
          readOnly: true
      volumes:
      - name: feast-config
        configMap:
          name: feast-config
      imagePullSecrets:
      - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: feast-feature-server-service
  namespace: ghosteam-v5
  labels:
    app: feast-feature-server
spec:
  selector:
    app: feast-feature-server
  ports:
  - protocol: TCP
    port: 6566
    targetPort: 6566
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: feast-config
  namespace: ghosteam-v5
data:
  feature_store.yaml: |
    project: ghosteam_v5
    registry: s3://ghosteam-v5-data/feast/registry.db
    provider: aws
    online_store:
      type: redis
      connection_string: redis-service:6379
    offline_store:
      type: s3
      s3_endpoint_url: https://s3.amazonaws.com
    entity_key_serialization_version: 2
