version: '3.8'

services:
  agi-system:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - RAILWAY_ENVIRONMENT=development
      - DATABASE_URL=sqlite:///data/agi_system.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./agents:/app/agents
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
