services:
  - type: web
    name: ghosteam-v5-autonomous
    env: python
    buildCommand: "pip install -r requirements.render.txt"
    startCommand: "python -m uvicorn src.autonomous_app:app --host 0.0.0.0 --port $PORT"
    plan: free
    healthCheckPath: "/health"
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: "1"
